# Generated by Django 4.2.11 on 2026-07-28 10:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('item_type', models.CharField(choices=[('SERVER', 'Server'), ('PRINTER', 'Printer'), ('CIRCUIT', 'Circuit'), ('FURNITURE', 'Furniture'), ('OTHER', 'Other')], max_length=20)),
                ('serial_number', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message='Serial number must be 16 alphanumeric characters.', regex='^[A-Za-z0-9]{16}$')])),
                ('demirbas_number', models.CharField(max_length=8, unique=True, validators=[django.core.validators.RegexValidator(message='Demirbas number must be 8 digits.', regex='^\\d{8}$')])),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=10, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
