# Generated by Django 6.0.7 on 2026-07-29 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_item_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='app.room'),
        ),
    ]
