# Generated by Django 6.0.7 on 2026-07-30 12:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_item_room'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='description',
            new_name='aciklama',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='name',
            new_name='bakanlik_adi',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='price',
            new_name='kiymet',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='item_type',
            new_name='malzeme_adi',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='room_number',
            new_name='room_name',
        ),
        migrations.RemoveField(
            model_name='item',
            name='demirbas_number',
        ),
        migrations.RemoveField(
            model_name='item',
            name='serial_number',
        ),
        migrations.AddField(
            model_name='item',
            name='ayniyat_no',
            field=models.CharField(max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Ayniyat number must be 6 digits.', regex='^\\d{6}$')]),
        ),
        migrations.AddField(
            model_name='item',
            name='daire_adi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='demirbas_no',
            field=models.CharField(max_length=17, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Demirbas number must be 17 digits.', regex='^\\d{17}$')]),
        ),
        migrations.AddField(
            model_name='item',
            name='fatura_no',
            field=models.CharField(max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Fatura number must be 6 digits.', regex='^\\d{6}$')]),
        ),
    ]
