# Generated by Django 6.0.7 on 2026-08-04 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_description_item_aciklama_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='room',
        ),
        migrations.AddField(
            model_name='item',
            name='allocated_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocated_items', to='app.room'),
        ),
        migrations.AddField(
            model_name='room',
            name='items',
            field=models.ManyToManyField(related_name='rooms', to='app.item'),
        ),
    ]
