# Generated by Django 6.0.7 on 2026-08-04 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_item_room_item_allocated_room_room_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='rooms', to='app.item'),
        ),
    ]
