# Generated by Django 6.0.7 on 2026-08-04 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_room_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='items',
        ),
        migrations.AlterField(
            model_name='item',
            name='malzeme_adi',
            field=models.CharField(choices=[('SERVER', 'SERVER'), ('PRINTER', 'PRINTER'), ('LAPTOP', 'LAPTOP'), ('TABLET', 'TABLET'), ('TELEVIZYON', 'TELEVIZYON'), ('TELEFON', 'TELEFON'), ('KEA', 'KUCUK EV ALETLERI'), ('MOBILYA', 'MOBILYA'), ('OTHER', 'DIGER MALZEMELER')], max_length=20),
        ),
    ]
