# Generated by Django 6.0.7 on 2026-08-06 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_room_items_alter_item_malzeme_adi'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('AKTIF', 'Aktif'), ('PASIF', 'Pasif')], default='ACTIVE', max_length=10),
        ),
        migrations.AlterField(
            model_name='item',
            name='malzeme_adi',
            field=models.CharField(choices=[('SERVER', 'SERVER'), ('PRINTER', 'PRINTER'), ('LAPTOP', 'LAPTOP'), ('TABLET', 'TABLET'), ('TELEVIZYON', 'TELEVIZYON'), ('TELEFON', 'TELEFON'), ('KUCUK EV ALETLERI', 'KUCUK EV ALETLERI'), ('MOBILYA', 'MOBILYA'), ('DIGER MALZEMELER', 'DIGER MALZEMELER')], max_length=20),
        ),
    ]
